# Generated by Django 5.1.15 on 2026-09-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bangla_name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='destinations/covers/')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bangla_name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('icon', models.CharField(blank=True, default='compass', help_text='Lucide/SVG icon name or emoji', max_length=50)),
            ],
            options={
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bangla_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('duration', models.CharField(default='3 Days / 2 Nights', max_length=80)),
                ('duration_days', models.PositiveSmallIntegerField(default=3, help_text='Number of days for filtering')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in BDT (৳)', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_travelers', models.PositiveIntegerField(default=20)),
                ('short_description', models.TextField(help_text='Short teaser for cards and search results')),
                ('description', models.TextField(help_text='Full itinerary and overview')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tours/covers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo preview link')),
                ('badge_text', models.CharField(blank=True, default='Featured', help_text='e.g. Popular, Hot Deal', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.destination')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.tourcategory')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_seats', models.PositiveIntegerField(default=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Departure Date',
                'verbose_name_plural': 'Tour Departure Dates',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour Gallery Image',
                'verbose_name_plural': 'Tour Gallery Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True, help_text='Checked = Included (✓), Unchecked = Excluded (✕)')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Inclusion / Exclusion',
                'verbose_name_plural': 'Inclusions & Exclusions',
            },
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meals', models.CharField(blank=True, help_text='e.g. Breakfast, Lunch, Dinner', max_length=150)),
                ('stay_info', models.CharField(blank=True, help_text='e.g. Eco Resort Sajek', max_length=150)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Itinerary Day',
                'verbose_name_plural': 'Itinerary Days',
                'ordering': ['day_number'],
            },
        ),
    ]
