# Generated by Django 5.1.15 on 2026-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='excluded_items',
            field=models.TextField(blank=True, help_text='What is not included (excluded) (one item per line)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_items',
            field=models.TextField(blank=True, help_text='What is included (one item per line)'),
        ),
        migrations.AddField(
            model_name='tourdate',
            name='total_capacity',
            field=models.PositiveIntegerField(default=40, help_text='Total batch capacity (e.g., 40 seats)'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='available_seats',
            field=models.PositiveIntegerField(default=40, help_text='Remaining available seats'),
        ),
    ]
