# Generated by Django 5.1.15 on 2026-09-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_excluded_items_tour_included_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='bangla_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='bangla_description',
            field=models.TextField(blank=True, help_text='Bengali full itinerary and overview'),
        ),
        migrations.AddField(
            model_name='tour',
            name='bangla_short_description',
            field=models.TextField(blank=True, help_text='Bengali teaser for cards and search results'),
        ),
        migrations.AddField(
            model_name='tourinclusion',
            name='bangla_item',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='bangla_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='bangla_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
