# Generated by Django 5.1.15 on 2026-09-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_destination_bangla_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bangla_excluded_items',
            field=models.TextField(blank=True, help_text='Bengali: What is not included (excluded) (one item per line)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='bangla_guide_security_info',
            field=models.CharField(blank=True, help_text='Bengali: Certified Guide & Safety Escort', max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='bangla_included_items',
            field=models.TextField(blank=True, help_text='Bengali: What is included (one item per line)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide_security_info',
            field=models.CharField(blank=True, default='Certified Guide & Safety Escort', help_text='e.g. Certified Guide & Safety Escort', max_length=200),
        ),
    ]
