# Generated by Django 5.1.15 on 2026-09-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_bangla_excluded_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bus_layout_type',
            field=models.CharField(choices=[('36', '36-Seater (4x9)'), ('40', '40-Seater (4x10)'), ('45', '45-Seater (5x9)')], default='40', help_text='Choose from three specific bus seat layouts: 36-seater, 40-seater, or 45-seater', max_length=10, verbose_name='Bus Seat Layout'),
        ),
        migrations.AddField(
            model_name='tour',
            name='has_bus_seat_selection',
            field=models.BooleanField(default=False, help_text='Provide an option to enable or disable bus seat selection per tour package', verbose_name='Enable Bus Seat Selection'),
        ),
        migrations.CreateModel(
            name='TourBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(default='Bus 1', help_text='e.g. Scania AC - Bus 1', max_length=100)),
                ('bus_number', models.CharField(blank=True, help_text='e.g. Dhaka Metro-Ba 14-8890', max_length=50)),
                ('layout_type', models.CharField(choices=[('36', '36-Seater (4x9)'), ('40', '40-Seater (4x10)'), ('45', '45-Seater (5x9)')], default='40', max_length=10)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='tours.tour')),
                ('tour_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='tours.tourdate')),
            ],
            options={
                'verbose_name': 'Tour Reserved Bus',
                'verbose_name_plural': 'Tour Reserved Buses',
                'ordering': ['tour', 'bus_name'],
            },
        ),
    ]
