# Generated by Django 5.1.15 on 2026-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_bus_layout_type_tour_has_bus_seat_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='requires_nid_or_birth_cert',
            field=models.BooleanField(default=True, help_text='Require travelers to upload NID or Birth Certificate when booking this package (e.g. hill tracts / border checkpoints)', verbose_name='Require NID or Birth Certificate'),
        ),
    ]
