# Generated by Django 5.1.15 on 2026-09-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_requires_nid_or_birth_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Corporate Event / Tour Title')),
                ('bangla_title', models.CharField(blank=True, max_length=255, verbose_name='Bangla Title (Optional)')),
                ('company_name', models.CharField(max_length=200, verbose_name='Client Company / Organization')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Focal Person Name')),
                ('designation', models.CharField(blank=True, max_length=150, verbose_name='Designation / Department')),
                ('phone', models.CharField(max_length=50, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('office_address', models.CharField(blank=True, max_length=255, verbose_name='Company / Office Address')),
                ('route_summary', models.CharField(blank=True, help_text="e.g. Dhaka -> Bandarban + Cox's Bazar -> Dhaka", max_length=255, verbose_name='Custom Route Summary')),
                ('start_date', models.DateField(verbose_name='Tour Start Date')),
                ('end_date', models.DateField(verbose_name='Tour End Date')),
                ('duration_text', models.CharField(default='3 Days / 2 Nights', max_length=100, verbose_name='Duration Description')),
                ('num_participants', models.PositiveIntegerField(default=50, verbose_name='Total Participants / Employees')),
                ('bus_count', models.PositiveIntegerField(default=1, verbose_name='Number of Buses Reserved')),
                ('bus_type', models.CharField(default='Luxury AC Coach (Hino / Scania)', max_length=150, verbose_name='Bus Type / Operator')),
                ('accommodation_details', models.TextField(blank=True, help_text='e.g. 5-Star Resort, Twin sharing executive rooms', verbose_name='Resort / Hotel Logistics')),
                ('catering_details', models.TextField(blank=True, help_text='e.g. Buffet breakfast, BBQ dinner, executive lunch sets', verbose_name='Food & Catering Logistics')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Package Budget (BDT)')),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Advance Paid Amount (BDT)')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending (বকেয়া)'), ('PARTIAL', 'Partially Paid / Advance Received (আংশিক পরিশোধ)'), ('PAID', 'Fully Paid (পরিশোধিত)')], default='PENDING', max_length=30, verbose_name='Payment Status')),
                ('special_requirements', models.TextField(blank=True, help_text='Conference hall, sound system, team building, banner setup', verbose_name='Client Special Requirements')),
                ('reminder_notes', models.TextField(blank=True, help_text='Internal notes for operations team, driver contacts, guide assignments', verbose_name='Administrative Reminders & Logistics Notes')),
                ('status', models.CharField(choices=[('PROPOSAL', 'Proposal / Planning (পরিকল্পনা)'), ('CONFIRMED', 'Confirmed (নিশ্চিত)'), ('IN_PROGRESS', 'In Progress / Traveling (চলমান)'), ('COMPLETED', 'Completed (সম্পন্ন)'), ('CANCELLED', 'Cancelled (বাতিল)')], default='PROPOSAL', max_length=30, verbose_name='Event Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(related_name='corporate_tours', to='tours.destination', verbose_name='Destinations Included')),
            ],
            options={
                'verbose_name': 'Corporate Tour & Event',
                'verbose_name_plural': 'Corporate Tours & Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200, verbose_name='Day Heading / Activity')),
                ('description', models.TextField(verbose_name='Activity / Schedule Details')),
                ('stay_info', models.CharField(blank=True, max_length=200, verbose_name='Night Stay / Location')),
                ('corporate_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='tours.corporatetour')),
            ],
            options={
                'verbose_name': 'Corporate Itinerary Day',
                'verbose_name_plural': 'Corporate Itinerary Days',
                'ordering': ['day_number'],
            },
        ),
    ]
