# Generated by Django 5.1.15 on 2026-09-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_corporatetour_corporateitinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration_type',
            field=models.CharField(choices=[('DAY_TOUR', 'Day Tour (Single Day / Day-Long)'), ('MULTI_DAY', 'Multi-Day Tour (e.g. 2 Nights / 3 Days)')], default='MULTI_DAY', help_text='Choose duration classification: Day Tour (Single Day / Day-Long) or Multi-Day Tour', max_length=20, verbose_name='Tour Duration Classification'),
        ),
    ]
