# Generated by Django 5.1.15 on 2026-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetour',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='corporate_tours/', verbose_name='Corporate Event Banner / Cover Image'),
        ),
        migrations.AddField(
            model_name='corporatetour',
            name='destination_name',
            field=models.CharField(blank=True, help_text='Any destination or venue across Bangladesh, e.g. Gazipur Resort, Savar, Sreemangal, Sundarbans', max_length=255, verbose_name='Event Venue / Destination'),
        ),
        migrations.AddField(
            model_name='corporatetour',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Feature on Corporate Showcase'),
        ),
        migrations.AddField(
            model_name='corporatetour',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Allow client and team to view bespoke corporate portal page online', verbose_name='Publish Corporate Portal Page'),
        ),
        migrations.AddField(
            model_name='corporatetour',
            name='vehicle_breakdown',
            field=models.TextField(blank=True, help_text='e.g. 4x 40-Seat Scania AC Buses, 2x HiAce Microbuses for executive committee, 1x Luggage Truck', verbose_name='Fleet & Transport Allocation Details'),
        ),
        migrations.AlterField(
            model_name='corporatetour',
            name='bus_type',
            field=models.CharField(default='Luxury AC Coach (Hino / Scania / Hyundai)', max_length=150, verbose_name='Bus Type / Fleet Allocation'),
        ),
        migrations.AlterField(
            model_name='corporatetour',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='corporate_tours', to='tours.destination', verbose_name='Catalog Destinations Included (Optional)'),
        ),
        migrations.AlterField(
            model_name='corporatetour',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cover_image',
            field=models.ImageField(help_text='Mandatory: Upload a distinct high-resolution landscape cover photo for this tour package card and hero banner.', null=True, upload_to='tours/covers/', verbose_name='Tour Cover Image (কভার ফটো)'),
        ),
    ]
