# Generated by Django 5.1.15 on 2026-09-16 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bangla_title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('author_name', models.CharField(default='ভ্রমণঘুড়ি টিম', max_length=120)),
                ('read_time', models.CharField(default='4 min read', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/covers/')),
                ('excerpt', models.TextField(help_text='Short teaser for story cards')),
                ('content', models.TextField(help_text='Full story / travel guide article')),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='tours.destination')),
            ],
            options={
                'verbose_name': 'Travel Story',
                'verbose_name_plural': 'Travel Stories',
                'ordering': ['-published_at'],
            },
        ),
    ]
