# Generated by Django 5.1.15 on 2026-09-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Author email for notifications/contact', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved / Published'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short teaser for story cards'),
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.story')),
            ],
            options={
                'verbose_name': 'Story Photo',
                'verbose_name_plural': 'Story Photos',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
