# Generated by Django 5.1.15 on 2026-09-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ভ্রমণঘুড়ি (Bhromonghuri)', max_length=100)),
                ('site_tagline_bn', models.CharField(default='নতুন জায়গা, নতুন গল্প, নতুন অনুভূতি', max_length=200)),
                ('site_tagline_en', models.CharField(default='Explore • Experience • Discover', max_length=200)),
                ('hero_headline', models.CharField(default='অদেখা বাংলাকে নতুন চোখে দেখা', max_length=255)),
                ('hero_subheadline', models.TextField(default='ভ্রমণঘুড়ির সাথে আবিষ্কার করুন পাহাড়, সমুদ্র, মেঘের দেশ আর সবুজ বনানীর অপূর্ব সৌন্দর্য। প্রতিটি পদক্ষেপে নিরাপদ ও রোমাঞ্চকর ভ্রমণ।')),
                ('phone', models.CharField(default='+880 1700-000000', max_length=30)),
                ('email', models.EmailField(default='info@bhromonghuri.com', max_length=254)),
                ('address', models.CharField(default='Dhaka, Bangladesh', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/bhromonghuri')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/bhromonghuri')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@bhromonghuri')),
                ('total_tours_count', models.CharField(default='50+', max_length=20)),
                ('total_travelers_count', models.CharField(default='1,500+', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('destinations_count', models.CharField(default='25+', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_designation', models.CharField(blank=True, help_text='e.g. Travel Enthusiast or Software Engineer', max_length=120)),
                ('tour_name', models.CharField(help_text='e.g. Sajek Valley Tour', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/')),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
