# Generated by Django 5.1.15 on 2026-09-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='bhromonghuri@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/share/g/19km9RqB1g/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='+8801518919370, 01855939459', max_length=60),
        ),
    ]
