# Generated by Django 5.1.15 on 2026-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bkash_number',
            field=models.CharField(default='01518919370 (Personal / Send Money)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nagad_number',
            field=models.CharField(default='01855939459 (Personal / Send Money)', max_length=100),
        ),
    ]
