# Generated by Django 5.1.15 on 2026-09-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_bkash_number_sitesetting_nagad_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_headline_bn',
            field=models.CharField(blank=True, default='অদেখা বাংলাকে নতুন চোখে দেখা', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subheadline_bn',
            field=models.TextField(blank=True, default='ভ্রমণঘুড়ির সাথে আবিষ্কার করুন পাহাড়, সমুদ্র, মেঘের দেশ আর সবুজ বনানীর অপূর্ব সৌন্দর্য। প্রতিটি পদক্ষেপে নিরাপদ ও রোমাঞ্চকর ভ্রমণ।'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_headline',
            field=models.CharField(default='Explore Unseen Bangladesh With Fresh Eyes', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subheadline',
            field=models.TextField(default='Discover mountains, cloud valleys, Sundarbans mangrove safari, and Saint Martin coral island with BhromonGhuri. Safe and thrilling travel every step of the way.'),
        ),
    ]
