# Generated by Django 5.1.15 on 2026-09-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_hero_headline_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='bkash_number',
            field=models.CharField(default='01855939459 (Personal / Send Money)', max_length=100),
        ),
    ]
