# Generated by Django 5.1.15 on 2026-09-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('category', models.CharField(choices=[('ALL', 'All Photos'), ('MOUNTAIN', 'Mountains & Hills (পাহাড়)'), ('BEACH', 'Beaches & Islands (সমুদ্র)'), ('FOREST', 'Forests & Lakes (বন ও হাওর)'), ('CULTURE', 'Culture & Local Life (ঐতিহ্য)'), ('GROUP', 'Travelers & Moments (স্মৃতি)')], default='MOUNTAIN', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on homepage gallery preview')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='tours.destination')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
