# Generated by Django 5.1.15 on 2026-09-23 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('tours', '0005_tour_bus_layout_type_tour_has_bus_seat_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='bangla_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='bangla_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='tours.tour'),
        ),
    ]
