# Generated by Django 5.1.15 on 2026-09-23 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_rejection_reason_alter_booking_status'),
        ('tours', '0005_tour_bus_layout_type_tour_has_bus_seat_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.tourbus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.CharField(blank=True, default='', help_text='Comma-separated chosen seat numbers (e.g. A1, A2)', max_length=150),
        ),
    ]
