# Generated by Django 5.1.15 on 2026-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_assigned_bus_booking_seat_selected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='identification_document',
            field=models.FileField(blank=True, help_text='Uploaded copy of NID, Birth Certificate, or Passport (Image/PDF)', null=True, upload_to='bookings/documents/', verbose_name='NID / Birth Certificate Document'),
        ),
        migrations.AddField(
            model_name='booking',
            name='identification_number',
            field=models.CharField(blank=True, default='', help_text='National ID, Birth Certificate, or Passport number', max_length=100, verbose_name='ID / Certificate Number'),
        ),
        migrations.AddField(
            model_name='booking',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('NID', 'National ID Card (NID)'), ('BIRTH_CERT', 'Birth Certificate'), ('PASSPORT', 'Passport / Student ID')], default='NID', max_length=50, verbose_name='Identification Document Type'),
        ),
    ]
