# Generated by Django 5.1.15 on 2026-09-23 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_identification_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('ONLINE', 'Online Customer (অনলাইন)'), ('OFFLINE', 'Admin / Offline Walk-in (অফলাইন/অন-স্পট)')], default='ONLINE', max_length=20, verbose_name='Booking Source'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Created By Admin'),
        ),
    ]
